# Site Info
title:              "Keep Coding"
description:        "Blog personal de Carlos Cañizares, .net, Azure, javascript, angular, docker, alm, filosofadas, eventos... en resumen otro blog más de un enfermo del desarrollo de software."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-91620071-1 # Put your Google Analytics code

# Author Info
author_name:        "Carlos Cañizares"
author_email:       c.canizaresestevez@hotmail.com
author_gravatar:    5ca9c02a828b2b514ea0af71cae8fb9a # Gravatar md5 hash
twitter_username:   ccanizares

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
